name: shopx
description: "ShopX App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models.
  flutter_screenutil: ^5.9.3
  # Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.5.3
  # networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.9.0
  # A carousel slider widget, support infinite scroll and custom child widget.
  carousel_slider: ^5.1.1
  # State management library that helps implement the BLoC (Business Logic Component) design pattern.
  flutter_bloc: ^9.1.1
  # This client makes it simple for developers to build secure and scalable products.
  supabase: ^2.10.0
  # This package makes it simple for developers to build secure and scalable products.
  supabase_flutter: ^2.10.3
  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: ^2.4.7
  # Package for easy use of images that are automatically cacheable and have a beautiful on the fly (but it can be configured) shimmer effect while loading.
  fancy_shimmer_image: ^2.0.3
  # Converts already built widgets into skeleton loaders with no extra effort.
  skeletonizer: ^2.1.0+1
  # A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps.
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^6.0.0
  flutter_facebook_auth: ^6.0.0
  fluttertoast: ^9.0.0
  get_it: ^9.0.5
  dartz: ^0.10.1




dev_dependencies:
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/banners/
    - assets/images/logos/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
